export type ProductCategory = 'inverter' | 'panel' | 'battery' | 'accessory';

export type Product = {
  id: string;
  category: ProductCategory;
  rawCategory?: string | null;
  rawSubCategory?: string | null;
  brand: string;
  brandName?: string | null;
  brandId?: string | null;
  brandSlug?: string | null;
  brandAliases?: string[];
  brandPriority?: number | null;
  brandPackageGenerationEnabled?: boolean | null;
  brandPackageImageUrl?: string | null;
  brandLogo?: string | null;
  productFamilyId?: string | null;
  brandDefaultCompatibilityGroup?: string | null;
  manufacturer?: string | null;
  brands?: {
    id?: string | null;
    name?: string | null;
    slug?: string | null;
    canonical_slug?: string | null;
    aliases?: string[] | null;
    priority?: number | null;
    package_generation_enabled?: boolean | null;
    package_image_url?: string | null;
    updated_at?: string | null;
    logo_url?: string | null;
    default_compatibility_group?: string | null;
  } | null;
  name: string;
  model?: string;
  image?: string;
  warranty?: string;
  capacity?: string;
  capacityWatt?: number | null;
  capacity_watt?: number | null;
  capacityKw?: number | null;
  batteryCapacityKwh?: number | null;
  usableCapacityKwh?: number | null;
  usableFactorOverride?: number | null;
  capacityValue?: number | null;
  capacityUnit?: string | null;
  capacityWh?: number | null;
  batteryCapacityStatus?: 'valid' | 'missing' | 'ambiguous' | 'implausible';
  batteryCapacityIssue?: string | null;
  panelWattage?: number | null;
  phase?: 'single' | 'three' | null;
  voltageClass?: 'LV' | 'HV' | 'NONE' | null;
  compatibilityGroups?: string[];
  parallelSupported?: boolean;
  maxParallelUnits?: number | null;
  sameModelParallelOnly?: boolean;
  maxParallelModules?: number | null;
  commercialMaxParallelModules?: number | null;
  maximumRecommendedPvKwp?: number | null;
  compatibleInverterBrandIds?: string[];
  compatibleBatteryBrandIds?: string[];
  panelWidthMm?: number | null;
  panelHeightMm?: number | null;
  commercialSpecStatus?: 'ready' | 'needs_review' | 'invalid' | null;
  sameBrandCompatibilityEnabled?: boolean;
  packageEligible?: boolean | null;
  priority?: number | null;
  isActive?: boolean | null;
  wattage?: number | string | null;
  power?: number | string | null;
  size?: number | string | null;
  priceUnit?: 'per_watt' | 'total_price' | null;
  ratePerWatt?: number | null;
  stockStatus?: string | null;
  isVisible?: boolean | null;
  subCategory?: string | null;
  specifications?: Record<string, unknown> | null;
  tag?: 'Recommended' | 'Best Value' | 'Premium' | 'Best Seller';
  price?: number | null;
  description?: string | null;
  accessorySubcategory?: string | null;
  shortSpec?: string | null;
  secondarySpec?: string | null;
  compareAtPrice?: number | null;
  currencyCode?: string | null;
  stockQuantity?: number | null;
  sku?: string | null;
  galleryImages?: string[];
  usageInstructions?: string | null;
  packageContents?: string | null;
  badge?: 'best_seller' | 'best_value' | 'new' | null;
  isFeatured?: boolean;
  updatedAt?: string | null;
  specs: string[];
};

export type MarketplaceBrand = {
  id: string;
  category: ProductCategory;
  name: string;
  slug?: string | null;
  canonicalSlug?: string | null;
  aliases?: string[];
  logoUrl?: string;
  updatedAt?: string | null;
};

export type MarketplaceCategory = {
  id: ProductCategory;
  title: string;
  subtitle: string;
};
